### ISSUE TITLE
Calendar displays an extra week (but not always)

### ISSUE THREAD

**Issue by IbrahimHd** [g1eb/angular-datetime-range#6]
Hi Gleb,

The Calendar displays an extra week in some months, please refer the below snapshot as an example:

![image](https://cloud.githubusercontent.com/assets/16100897/21710997/ea24e06e-d3f4-11e6-9276-65c281b714fb.png)

**Comment by g1eb** [comment]
Nice find! I've fixed it in v0.2.9 👍

**Comment by IbrahimHd** [comment]
great 👍

**Comment by IbrahimHd** [comment]
unfortunately, it's still showing an extra week in the calendar!
Plz try to navigate to March 2017 and you can notice the extra week at the bottom

**Comment by g1eb** [comment]
I've checked this and can't see the extra week in March 2017, here's a screenshot:

<img width="490" alt="screen shot 2017-01-06 at 3 20 54 pm" src="https://cloud.githubusercontent.com/assets/1916056/21720590/4ec95bf6-d424-11e6-89f3-7020e6299fee.png">

Are you using the latest version? (v0.2.9)

**Comment by IbrahimHd** [comment]
it appears in the online demo page (maybe the html/angular code is not updated?
![image](https://cloud.githubusercontent.com/assets/16100897/21721078/424b85e2-d42f-11e6-8dc6-02b9093eac73.png)

**Comment by g1eb** [comment]
Ah.. interesting, because my screen shot was taken on the demo page :)

I suspect a caching issue here, have you tried to clear cache or force-reload the page?
(Ctrl + F5 on windows, Command + R on mac)

**Comment by IbrahimHd** [comment]
Believe me I did it before sending my comment and it still appears at my side in the demo page and my dev enviro as well!!
I have v0.2.9

**Comment by g1eb** [comment]
Hi, is this still an issue? I'd love to look into this but I need something to reproduce this with..

**Comment by IbrahimHd** [comment]
Unfortunately yes!
I'm checking the online demo and it gives extra week (March 2017) on both Chrome and MS Edge and even after cleaning the cache.

**Comment by g1eb** [comment]
Hi, I've just tested this on IE11 and IE10 and I still can't reproduce this. Maybe this has to do with locale settings on your machine?

Could you tell me specifications of the environment where this issue occurs?

Thanks for testing this, I appreciate your efforts and I want to fix this for you :)

**Comment by IbrahimHd** [comment]
That's really odd!
I can see the extra week (eg. March 2017) on both the online demo and at my local app after cleaning the cache.
This is my enviro:
OS: Windows 10
Browser: Chrome v55.0.2883.87 (64-bit)
Locale/Region: United States

Thanks for your effort!

**Comment by g1eb** [comment]
Hm, very strange indeed, I've checked this again just now.

Not quite sure what the source of the issue is.
Have you tried this on a different machine/environment?

**Comment by IbrahimHd** [comment]
I'm experiencing this issue in two different computers with almost similar specs.

**Comment by g1eb** [comment]
Yeah, it's a very strange, I've asked friends to test this for me on their machines and it worked for them. Also tried updating locale settings to us, such as week starts on Sunday etc. all works fine for me :|

Anyways, I've moved ```getNumWeeks``` function to calculate number of weeks in a month to directive link function for debugging purposes and pushed it to master. [Demo](https://rawgit.com/g1eb/angular-datetime-range/master/) should be updated too, although you might have to clear your cache. Could you please check again? :)

For debugging purposes you can log what ```getNumWeeks``` function returns on line 40 in ```src/datetime-range.js```.

PS. If this works I will update the other inputs repo as well, same calendar issue there I believe.

**Comment by IbrahimHd** [comment]
Hi Gleb,

Sorry for my late reply.
The `getNumWeeks` returns the following:

- For Feb 2017: **5** (correct)
- For March 2017: **6** (should be **5**)
- For April 2017: **6** (correct)

And `getNumWeeks` keeps firing every 2 seconds even if the directive is closed.

Hopeful this is informative.
Thnx

**Comment by g1eb** [comment]
Hi! No worries, thank you for looking into with this one with me :)

I'll take another shot at this asap and get back to you!

**Comment by g1eb** [comment]
Hi there :)

I've updated `getNumWeeks` functionality to use a new approach to calculate number of weeks in a month, here is a quick fiddle to test: [https://jsfiddle.net/3ww30vyt/4/](https://jsfiddle.net/3ww30vyt/4/)

I've added this feature to the latest version (v0.2.13)

**Comment by g1eb** [comment]
Closing due to extended period of inactivity and not being able to reproduce this issue in general
